package com.base.plugin;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.generator.BaseModelGenerator;
import com.jfinal.plugin.activerecord.generator.ColumnMeta;
import com.jfinal.plugin.activerecord.generator.TableMeta;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 * Jfinal代码生成器插件，加入BaseModel方便扩展代码分享
 *
 * @author ChenMW 2016-03-16 16:18
 */
public class MyBaseModelGenerator extends BaseModelGenerator{

    protected String classDefineTemplate =
            "/**%n" +
            " * MyGenerated by JFinal, do not modify this file.%n" +
            " */%n" +
            "@SuppressWarnings(\"serial\")%n" +
            "public abstract class %s<M extends %s<M>> extends %s<M> implements IBean {%n%n";

    //baseModel的父类模板
    protected String superClassDefineTemplate =
            "/**%n" +
            " * MyGenerated by JFinal, do not modify this file.%n" +
            " */%n" +
            "@SuppressWarnings(\"serial\")%n" +
            "public abstract class %s<M extends %s<M>> extends Model<M> {%n%n";

    //baseModel类属性模板
    String classFieldTemplate =
            "\tpublic final static String TABLE_NAME = \"%s\";%n%n" +
            "\tpublic final static String SQL = \"SELECT * FROM %s WHERE 1=1 \";%n%n";
    //String String
    protected Boolean isExistBaseModeSuperClass = false;
    protected String baseModeSuperClassSimpleName;

    public MyBaseModelGenerator(String baseModelPackageName, String baseModelOutputDir) {
        super(baseModelPackageName,baseModelOutputDir);
    }

    /**
     * @param baseModelPackageName              baseModel 所使用的包名
     * @param baseModelOutputDir                baseModel 输出路径
     * @param baseModeSuperClassSimpleName      baseModel 的父类的类名，承载整个Model业务的公共方法
     */
    public MyBaseModelGenerator(String baseModelPackageName, String baseModelOutputDir,String baseModeSuperClassSimpleName) {
        this(baseModelPackageName,baseModelOutputDir);
        if(StrKit.notBlank(baseModeSuperClassSimpleName)){
            this.isExistBaseModeSuperClass = true;
            this.baseModeSuperClassSimpleName = baseModeSuperClassSimpleName;
            this.importTemplate = "import com.jfinal.plugin.activerecord.IBean;%n%n";
        }
    }

    /**
     *  重写
     */
    public void generate(List<TableMeta> tableMetas) {
        System.out.println("正在生成 baseModel ...");
        if(isExistBaseModeSuperClass){
            this.genBaseModelSuperClass();
        }
        for (TableMeta tableMeta : tableMetas) {
            genBaseModelContent(tableMeta);
        }
        wirtToFile(tableMetas);
    }

    /**
     * 重写
     */
    protected void genBaseModelContent(TableMeta tableMeta) {
        StringBuilder ret = new StringBuilder();
        genPackage(ret);
        genImport(ret);
        genClassDefine(tableMeta, ret);
        //在baseModels中添加表名称的属性
        ret.append(String.format(classFieldTemplate,tableMeta.name,tableMeta.name));

        for (ColumnMeta columnMeta : tableMeta.columnMetas) {
            genSetMethodName(columnMeta, ret);
            genGetMethodName(columnMeta, ret);
        }
        ret.append(String.format("}%n"));
        tableMeta.baseModelContent = ret.toString();
    }

    /**
     * 重写
     */
    protected void genClassDefine(TableMeta tableMeta, StringBuilder ret) {
        ret.append(String.format(classDefineTemplate, tableMeta.baseModelName, tableMeta.baseModelName,isExistBaseModeSuperClass?baseModeSuperClassSimpleName:"Model"));
    }

    /**
     * 重写
     */
    protected void wirtToFile(List<TableMeta> tableMetas) {
        try {
            for (TableMeta tableMeta : tableMetas)
                wirtToFile(tableMeta,false);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * 新增 生成 baseModel 类的父类
     */
    protected void genBaseModelSuperClass(){
        TableMeta baseModelSuperClassTableMeta = new TableMeta();
        baseModelSuperClassTableMeta.baseModelName=baseModeSuperClassSimpleName;
        StringBuilder ret = new StringBuilder();
        genPackage(ret);
        ret.append(String.format("import com.jfinal.plugin.activerecord.Model;%n%n"));
        ret.append(String.format(superClassDefineTemplate,baseModeSuperClassSimpleName,baseModeSuperClassSimpleName));
        ret.append(String.format("}%n"));
        baseModelSuperClassTableMeta.baseModelContent = ret.toString();
        try {
            wirtToFile(baseModelSuperClassTableMeta,true);
        } catch (IOException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }

    /**
     * 新增，写入文件
     */
    protected void wirtToFile(TableMeta tableMeta,Boolean isBaseModelSpuerClass) throws IOException {
        File dir = new File(baseModelOutputDir);
        if (!dir.exists())
            dir.mkdirs();

        String target = baseModelOutputDir + File.separator + tableMeta.baseModelName + ".java";
        //新增判断
        if(isBaseModelSpuerClass){
            if (new File(target).exists()) {
                return;
            }
        }
        FileWriter fw = new FileWriter(target);
        try {
            fw.write(tableMeta.baseModelContent);
        }finally {
            fw.close();
        }
    }
}
