package com.mi2.model;

import com.base.model.BaseGoodsColor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsColor extends BaseGoodsColor<GoodsColor> {
	public static final GoodsColor dao = new GoodsColor();
}
