package com.mi2.model;

import com.base.model.BaseGoodsAssess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsAssess extends BaseGoodsAssess<GoodsAssess> {
	public static final GoodsAssess dao = new GoodsAssess();
}
