package com.mi2.model;

import com.base.model.BaseGoodsAdapterPhone;
import com.jfinal.plugin.activerecord.Db;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsAdapterPhone extends BaseGoodsAdapterPhone<GoodsAdapterPhone> {
	public static final GoodsAdapterPhone dao = new GoodsAdapterPhone();

	/**
	 * 批量修改商品适配的机型
	 * @param goodsId 				商品编号
	 * @param phoneSmallTypeIdsStr	手机机型
	 */
	public void batchUpdate(BigDecimal goodsId, String phoneSmallTypeIdsStr){
		this.batchDelete(goodsId);
		this.batchSave(goodsId,phoneSmallTypeIdsStr);
	}

	/**
	 * 批量删除商品适配的机型
	 * @param goodsId 商品编号
     */
	public int batchDelete(BigDecimal goodsId){
		String sql = "delete goods_adapter_phone gap where gap.goods_id=?";
		return Db.update(sql,goodsId);
	}

	@Override
	public List<GoodsAdapterPhone> getAllData(GoodsAdapterPhone t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("select * from goods_adapter_phone gap where 1=1 ");
		ArrayList<Object> values = new ArrayList<>();
		if(t!=null&&!t.getAttrs().isEmpty()){
			if(t.getGoodsId()!=null){
				sbSql.append(" and gap.goods_id=?");
				values.add(t.getGoodsId());
			}
			if(t.getGoodsSmallTypeId()!=null){
				sbSql.append(" and gap.goods_small_type_id=?");
				values.add(t.getGoodsSmallTypeId());
			}
		}
		return this.find(sbSql.toString(),values.toArray());
	}

	/**
	 * 批量保存商品适配的机型
	 * @param goodsId 				商品编号
	 * @param phoneSmallTypeIdsStr	手机机型
     * @return						返回保存结果
     */
	public int[] batchSave(BigDecimal goodsId, String phoneSmallTypeIdsStr){
		String[] phoneSmallTypeIds = phoneSmallTypeIdsStr.split(",");
		List<GoodsAdapterPhone> goodsAdapterPhoneList = new ArrayList<>();
		for(String phoneSmallTypeId : phoneSmallTypeIds){
			GoodsAdapterPhone goodsAdapterPhone = new GoodsAdapterPhone();
			goodsAdapterPhone.setGoodsId(goodsId);
			goodsAdapterPhone.setGoodsSmallTypeId(BigDecimal.valueOf(Long.parseLong(phoneSmallTypeId)));
			goodsAdapterPhoneList.add(goodsAdapterPhone);
		}
		return Db.batchSave(goodsAdapterPhoneList,goodsAdapterPhoneList.size());
	}
}
