package com.mi2.model;

import com.base.model.BaseGoodsAddributeVal;
import com.base.model.IService;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsAddributeVal extends BaseGoodsAddributeVal<GoodsAddributeVal> implements IService<GoodsAddributeVal> {
	public static final GoodsAddributeVal dao = new GoodsAddributeVal();

	@Override
	public List<GoodsAddributeVal> getAllData(GoodsAddributeVal goodsAddributeVal) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("select * from goods_addribute_val gav where 1=1 ");
		return this.find(sbSql.toString());
	}

	@Override
	public Page<GoodsAddributeVal> getAllDataByPage(int pageNumber, int pageSize, GoodsAddributeVal goodsAddributeVal) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("from goods_addribute ga,goods_addribute_val gav where ga.goods_addribute_id=gav.goods_addribute_id ");
		ArrayList<Object> values = new ArrayList<>();
		if(goodsAddributeVal!=null&&!goodsAddributeVal.getAttrs().isEmpty()){
			if(StrKit.notBlank(goodsAddributeVal.getGoodsAddributeValName())){
				sbSql.append(" and gav.goods_addribute_val_name like ?");
				values.add("%"+goodsAddributeVal.getGoodsAddributeValName()+"%");
			}
			if(goodsAddributeVal.getGoodsAddributeId()!=null){
				sbSql.append(" and gav.goods_addribute_id = ?");
				values.add(goodsAddributeVal.getGoodsAddributeId());
			}
		}
		return this.paginate(pageNumber,pageSize,"select ga.goods_addribute_name,gav.* ",sbSql.toString(),values.toArray());
	}
}
