package com.mi2.model;

import com.base.model.BaseGoodsImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsImages extends BaseGoodsImages<GoodsImages> {
	public static final GoodsImages dao = new GoodsImages();
}
