package com.mi2.model;

import com.base.model.BaseGoods;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods>{
	public static final Goods dao = new Goods();

	//获得缺货商品列表
	public List<Goods> getOutStockGoods(){
		String sql = "select g.*,gbt.goods_bigl_type_name,gst.goods_small_type_name,gst.goods_small_type_remark,gst.goods_small_type_image from goods_big_type gbt,goods_small_type gst,goods g where gbt.goods_big_type_id=gst.goods_big_type_id and gst.goods_small_type_id=g.goods_small_type_id and g.goods_stock<=10 order by g.goods_stock";
		return this.find(sql);
	}

	//获取商品销量按照商品小类别汇总
	public List<Goods> getGoodsSalesBySmallTypeSum(){
		String sql = "select gst.goods_small_type_name,t.goods_sum_sales goods_small_type_stock from(select g.goods_small_type_id,sum(g.goods_sales_num) goods_sum_sales from goods g group by g.goods_small_type_id having sum(g.goods_sales_num)>0)t,goods_small_type gst where gst.goods_small_type_id = t.goods_small_type_id";
		return this.find(sql);
	}

	//获取商品库存总量和销售总量
	public Goods getSumGoodsStockAndSales(){
		String sql = "select sum(g.goods_stock) goods_sum_stock,sum(g.goods_sales_num) goods_sum_sales from goods g";
		return this.findFirst(sql);
	}

	//删除其他商品信息
	public boolean deletePhoneGoods(Goods t){
		//删除其他商品图片信息
		new GoodsColor().deleteOtherGoodsColor(t.getGoodsId());
		//删除其他商品适配机型信息
		new GoodsAdapterPhone().batchDelete(t.getGoodsId());
		//删除商品基本信息
		return new Goods().deleteById(t.getGoodsId());
	}

	public Goods findById(BigDecimal goodsId) {
		if(null==goodsId){
			return null;
		}
		Goods t = new Goods();
		t.setGoodsId(goodsId);
		List<Goods> goodsList = this.getAllData(t);
		return goodsList.size()>0?goodsList.get(0):null;
	}

	@Override
	public Page<Goods> getAllDataByPage(int pageNumber, int pageSize, Goods t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("from goods_big_type gbt,goods_small_type gst,goods g where gbt.goods_big_type_id = gst.goods_big_type_id and gst.goods_small_type_id = g.goods_small_type_id ");
		ArrayList<Object> values = new ArrayList<>();
		if(t!=null&&!t.getAttrs().isEmpty()){
			if(StrKit.notBlank(t.getStr("goods_big_type_id"))){
				sbSql.append(" and gst.goods_big_type_id=?");
				values.add(t.getStr("goods_big_type_id"));
			}
			if(StrKit.notBlank(t.getGoodsName())){
				sbSql.append(" and g.goods_name like ?");
				values.add("%"+t.getGoodsName()+"%");
			}
			if(t.getGoodsSmallTypeId()!=null){
				sbSql.append(" and gst.goods_small_type_id=?");
				values.add(t.getGoodsSmallTypeId());
			}
			//判断该商品是否匹配当前机型
			if(StrKit.notBlank(t.getStr("phone_small_type_id"))){
				sbSql.append(" and exists(select g.goods_id from goods_adapter_phone gap where gap.goods_id=g.goods_id and gap.goods_small_type_id=?)");
				values.add(t.getStr("phone_small_type_id"));
			}
		}
		return this.paginate(pageNumber,pageSize,"select gbt.*,gst.goods_small_type_name,g.* ",sbSql.toString(),values.toArray());
	}

	@Override
	public List<Goods> getAllData(Goods t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("select gbt.*,gst.goods_small_type_name,g.* from goods_big_type gbt,goods_small_type gst,goods g where gbt.goods_big_type_id = gst.goods_big_type_id and gst.goods_small_type_id = g.goods_small_type_id ");
		ArrayList<Object> values = new ArrayList<>();
		if(t!=null&&!t.getAttrs().isEmpty()){
			if(StrKit.notBlank(t.getStr("goods_big_type_id"))){
				sbSql.append(" and gst.goods_big_type_id=?");
				values.add(t.getStr("goods_big_type_id"));
			}
			if(t.getGoodsSmallTypeId()!=null){
				sbSql.append(" and gst.goods_small_type_id=?");
				values.add(t.getGoodsSmallTypeId());
			}
			if(t.getGoodsId()!=null){
				sbSql.append(" and g.goods_id = ?");
				values.add(t.getGoodsId());
			}
			if(StrKit.notBlank(t.getGoodsName())){
				sbSql.append(" and g.goods_name like ?");
				values.add("%"+t.getGoodsName()+"%");
			}
		}
		return this.find(sbSql.toString(),values.toArray());
	}
}
