package com.mi2.model;

import com.base.model.BasePhoneSetmeal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneSetmeal extends BasePhoneSetmeal<PhoneSetmeal> {
	public static final PhoneSetmeal dao = new PhoneSetmeal();
}
