package com.mi2.model;

import com.base.model.BasePhoneSetmealDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneSetmealDetail extends BasePhoneSetmealDetail<PhoneSetmealDetail> {
	public static final PhoneSetmealDetail dao = new PhoneSetmealDetail();
}
