package com.mi2.model;

import com.base.model.BasePhoneSetmeal;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.util.ArrayList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneSetmeal extends BasePhoneSetmeal<PhoneSetmeal> {
	public static final PhoneSetmeal dao = new PhoneSetmeal();

	@Override
	public Page<PhoneSetmeal> getAllDataByPage(int pageNumber, int pageSize, PhoneSetmeal t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("from goods_small_type gst,phone_setmeal ps where gst.goods_big_type_id=1 and gst.goods_small_type_id=ps.goods_small_type_id");
		ArrayList<Object> values = new ArrayList<>();
		if(t!=null&&!t.getAttrs().isEmpty()){
			if(t.getGoodsSmallTypeId()!=null){
				sbSql.append(" and ps.goods_small_type_id=?");
				values.add(t.getGoodsSmallTypeId());
			}
			if(StrKit.notBlank(t.getPhoneSetmealName())){
				sbSql.append(" and ps.phone_setmeal_name like ?");
				values.add("%"+t.getPhoneSetmealName()+"%");
			}
		}
		return this.paginate(pageNumber,pageSize,"select gst.goods_small_type_name,ps.* ",sbSql.toString(),values.toArray());
	}
}
