package com.mi2.model;

import com.base.model.BasePhoneVersion;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneVersion extends BasePhoneVersion<PhoneVersion> {
	public static final PhoneVersion dao = new PhoneVersion();

	//获取手机商品销量按照商品小类别汇总
	public List<PhoneVersion> getPhoneGoodsSalesBySmallTypeSum(){
		String sql = "select gst.goods_small_type_name,t.goods_sum_sales goods_small_type_stock from(select pm.goods_small_type_id,sum(pv.phone_sales_num) goods_sum_sales from phone_model pm,phone_version pv where pm.model_id = pv.model_id group by pm.goods_small_type_id having sum(pv.phone_sales_num)>0)t,goods_small_type gst where gst.goods_small_type_id = t.goods_small_type_id";
		return this.find(sql);
	}

	//获取商品库存总量和销售总量
	public PhoneVersion getSumPhoneGoodsStockAndSales(){
		String sql = "select sum(pv.phone_stock) goods_sum_stock,sum(pv.phone_sales_num) goods_sum_sales from phone_version pv";
		return this.findFirst(sql);
	}
}
