package com.mi2.model;

import com.base.model.BasePhoneModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneModel extends BasePhoneModel<PhoneModel> {
	public static final PhoneModel dao = new PhoneModel();
}
