package com.mi2.model;

import com.base.model.BasePhoneGoodsView;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneGoodsView extends BasePhoneGoodsView<PhoneGoodsView> {
	public static final PhoneGoodsView dao = new PhoneGoodsView();
}
