package com.mi2.model;

import com.base.model.BasePhoneVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneVersion extends BasePhoneVersion<PhoneVersion> {
	public static final PhoneVersion dao = new PhoneVersion();
}
