package com.mi2.model;

import com.base.model.BasePhoneSetmealDetail;
import com.jfinal.plugin.activerecord.Db;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneSetmealDetail extends BasePhoneSetmealDetail<PhoneSetmealDetail> {
	public static final PhoneSetmealDetail dao = new PhoneSetmealDetail();

	@Override
	public List<PhoneSetmealDetail> getAllData(PhoneSetmealDetail t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("select g.*,psd.phone_setmeal_detail_id,psd.phone_setmeal_id,psd.goods_num from phone_setmeal_detail psd,goods g where psd.goods_id = g.goods_id ");
		ArrayList<Object> values = new ArrayList<>();
		if(null!=t&&!t.getAttrs().isEmpty()){
			if(t.getPhoneSetmealId()!=null){
				sbSql.append(" and psd.phone_setmeal_id=?");
				values.add(t.getPhoneSetmealId());
			}
		}
		return this.find(sbSql.toString(),values.toArray());
	}

	public void batchUpdate(BigDecimal phoneSetmealId, List<Map<String,String>> phoneSetmealGoodsList){
		this.batchDelete(phoneSetmealId);
		this.batchSave(phoneSetmealId,phoneSetmealGoodsList);
	}

	public int batchDelete(BigDecimal phoneSetmealId){
		String sql = "delete phone_setmeal_detail psd where psd.phone_setmeal_id=?";
		return Db.update(sql,phoneSetmealId);
	}

	public int[] batchSave(BigDecimal phoneSetmealId, List<Map<String,String>> phoneSetmealGoodsList){
		List<PhoneSetmealDetail> psdList = new ArrayList<>();
		for(Map<String,String> map : phoneSetmealGoodsList){
			PhoneSetmealDetail psd = new PhoneSetmealDetail();
			psd.setPhoneSetmealId(phoneSetmealId);
			psd.setGoodsId(BigDecimal.valueOf(Long.parseLong(map.get("goods_id"))));
			psd.setGoodsNum(BigDecimal.valueOf(Long.parseLong(map.get("goods_num"))));
			psdList.add(psd);
		}
		if(psdList.size()==0){
			return null;
		}
		return Db.batchSave(psdList,psdList.size());
	}
}
