package com.mi2.model;

import com.base.model.BasePhoneModel;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhoneModel extends BasePhoneModel<PhoneModel> {
	public static final PhoneModel dao = new PhoneModel();

	public PhoneModel findById(PhoneModel phoneModel) {
		List<PhoneModel> phoneModelList = this.getAllData(phoneModel);
		return phoneModelList.size()>0?phoneModelList.get(0):null;
	}

	@Override
	public List<PhoneModel> getAllData(PhoneModel t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("select * from phone_model pm where 1=1 ");
		ArrayList<Object> values = new ArrayList<>();
		if(t!=null&&!t.getAttrs().isEmpty()){
			if(t.getGoodsSmallTypeId()!=null){
				sbSql.append(" and pm.goods_small_type_id=?");
				values.add(t.getGoodsSmallTypeId());
			}
			if(t.getGoodsAddributeValId()!=null){
				sbSql.append(" and pm.goods_addribute_val_id=?");
				values.add(t.getGoodsAddributeValId());
			}
		}
		return this.find(sbSql.toString(),values.toArray());
	}
}
