package com.mi2.model;

import com.base.model.BaseShopcarPhoneSetmealGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopcarPhoneSetmealGoods extends BaseShopcarPhoneSetmealGoods<ShopcarPhoneSetmealGoods> {
	public static final ShopcarPhoneSetmealGoods dao = new ShopcarPhoneSetmealGoods();
}
