package com.mi2.model;

import com.base.model.BaseSysMenu;
import com.jfinal.plugin.activerecord.Page;

import java.math.BigDecimal;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu();

	public List<SysMenu> getUserMenuList(BigDecimal roleGroupId){
		String sql = "select sm.* from sys_role_group srg,group_menu gm,sys_menu sm where srg.role_group_id=gm.role_group_id and gm.menu_id=sm.menu_id and srg.role_group_id=?";
		return this.find(sql,roleGroupId);
	}

	@Override
	public List<SysMenu> getAllData(SysMenu sysMenu) {
		String sql = "select * from sys_menu where 1=1 ";
		return this.find(sql);
	}

	@Override
	public Page<SysMenu> getAllDataByPage(int pageNumber, int pageSize, SysMenu sysMenu) {
		return null;
	}
}
