package com.mi2.model;

import com.base.model.BaseSysRoleGroup;
import com.base.model.IService;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
public class SysRoleGroup extends BaseSysRoleGroup<SysRoleGroup> implements IService<SysRoleGroup>{
	public static final SysRoleGroup dao = new SysRoleGroup();

	//保存
	public void save(SysRoleGroup t,String menuIdsStr){
		SysRoleGroup sysRoleGroup = new SysRoleGroup();
		sysRoleGroup._setAttrs(t);
		sysRoleGroup.save();
		//批量保存菜单权限
		new GroupMenu().batchSave(sysRoleGroup.getRoleGroupId(),menuIdsStr);
	}

	//更新
	public void update(SysRoleGroup t,String menuIdsStr){
		this._setAttrs(t).update();
		GroupMenu groupMenu = new GroupMenu();
		groupMenu.batchDelete(t.getRoleGroupId());
		groupMenu.batchSave(t.getRoleGroupId(),menuIdsStr);
	}

	//删除
	public void delete(SysRoleGroup t){
		new GroupMenu().batchDelete(t.getRoleGroupId());
		this._setAttrs(t).delete();
	}

	@Override
	public List<SysRoleGroup> getAllData(SysRoleGroup sysRoleGroup) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("select * from sys_role_group where 1=1");
		return this.find(sbSql.toString());
	}

	@Override
	public Page<SysRoleGroup> getAllDataByPage(int pageNumber, int pageSize, SysRoleGroup sysRoleGroup) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("from sys_role_group srg where 1=1 ");
		ArrayList<Object> values = new ArrayList<>();
		if(sysRoleGroup!=null&&!sysRoleGroup.getAttrs().isEmpty()){
			if(StrKit.notBlank(sysRoleGroup.getRoleGroupName())){
				sbSql.append(" and srg.role_group_name like ?");
				values.add("%"+sysRoleGroup.getRoleGroupName()+"%");
			}
		}
		return this.paginate(pageNumber,pageSize,"select * ",sbSql.toString(),values.toArray());
	}
}
