package com.mi2.model;

import com.base.model.BaseUsersFront;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersFront extends BaseUsersFront<UsersFront> {
	public static final UsersFront dao = new UsersFront();
}
