package com.mi2.model;

import com.base.model.BaseUsersDeliveryAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersDeliveryAddress extends BaseUsersDeliveryAddress<UsersDeliveryAddress> {
	public static final UsersDeliveryAddress dao = new UsersDeliveryAddress();
}
