package com.mi2.model;

import com.base.model.BaseUsersShopcarSetmealGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersShopcarSetmealGoods extends BaseUsersShopcarSetmealGoods<UsersShopcarSetmealGoods> {
	public static final UsersShopcarSetmealGoods dao = new UsersShopcarSetmealGoods();
}
