package com.mi2.model;

import com.base.model.BaseUsersOrdersDetail;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersOrdersDetail extends BaseUsersOrdersDetail<UsersOrdersDetail> {
	public static final UsersOrdersDetail dao = new UsersOrdersDetail();

	//获取订单其他商品详情信息
	public List<UsersOrdersDetail> getOtherGoodsAllData(UsersOrders t) {
		/*if(t==null||t.getOrdersId()==null){
			return new ArrayList<>();
		}*/
		String sql = "select ogv.*,uod.orders_details_id,uod.orders_id,uod.cost_num,uod.cost_price,gc.goods_color_img_url,gav.goods_addribute_val_name,gav.goods_color_code from users_orders_detail uod,other_goods_view ogv,goods_color gc,goods_addribute_val gav where uod.phone_goods_id is null and uod.goods_id = ogv.goods_id and uod.goods_color_id=gc.goods_color_id and gc.goods_addribute_val_id=gav.goods_addribute_val_id and (ogv.adapt_phone_type_id is null or uod.adapt_phone_type_id=ogv.adapt_phone_type_id) and uod.orders_id=?";
		return this.find(sql,t.getOrdersId());
	}

	//获取订单手机商品详情信息
	public List<UsersOrdersDetail> getPhoneGoodsAllData(UsersOrders t) {
		/*if(t==null||t.getOrdersId()==null){
			return new ArrayList<>();
		}*/
		String sql = "select pgv.*,uod.orders_details_id,uod.orders_id,uod.cost_num,uod.cost_price,gc.goods_color_img_url,gav.goods_addribute_val_name,gav.goods_color_code from users_orders_detail uod,phone_goods_view pgv,goods_color gc,goods_addribute_val gav where uod.goods_id is null and uod.phone_goods_id=pgv.phone_goods_id and uod.goods_color_id=gc.goods_color_id and gc.goods_addribute_val_id=gav.goods_addribute_val_id and uod.orders_id=? ";
		return this.find(sql,t.getOrdersId());
	}

	public int batchSaveOrdersDetail(UsersOrders usersOrders){
		if(null!=usersOrders&&usersOrders.getUserFrontId()!=null&&usersOrders.getOrdersId()!=null){
			//保存商品到订单详情表中
			String sql = "insert into users_orders_detail(orders_id,goods_id,cost_num,cost_price,phone_goods_id,goods_color_id,adapt_phone_type_id) select ? orders_id,usav.goods_id,usav.cost_num,usav.cost_price,usav.phone_goods_id,usav.goods_color_id,usav.adapt_phone_type_id from users_settle_acounts_view usav where usav.user_front_id=?";
			return Db.update(sql,usersOrders.getOrdersId(),usersOrders.getUserFrontId());
		}
		return 0;
	}
}
