package com.mi2.model;

import com.base.model.BaseUsersShopcarSetmealGoods;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersShopcarSetmealGoods extends BaseUsersShopcarSetmealGoods<UsersShopcarSetmealGoods> {
	public static final UsersShopcarSetmealGoods dao = new UsersShopcarSetmealGoods();

	@Override
	public List<UsersShopcarSetmealGoods> getAllData(UsersShopcarSetmealGoods t) {
		String sql = "select g.*,ussg.users_shopcar_setmeal_goods_id,ussg.users_shopping_id,ussg.goods_color_id,ussg.goods_num,ussg.status,ussg.adapt_phone_type_id,gc.goods_color_img_url,gav.goods_addribute_val_name goods_color_name,gav.goods_color_code from users_shopcar_setmeal_goods ussg,goods g,goods_color gc,goods_addribute_val gav where ussg.goods_id = g.goods_id and ussg.goods_color_id = gc.goods_color_id and gc.goods_addribute_val_id = gav.goods_addribute_val_id and ussg.users_shopping_id=?";
		return this.find(sql,t.getUsersShoppingId());
	}
}
