package com.mi2.model;

import com.base.model.BaseUsersOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersOrders extends BaseUsersOrders<UsersOrders> {
	public static final UsersOrders dao = new UsersOrders();
}
