package com.mi2.model;

import com.base.model.BaseUsersDeliveryAddress;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersDeliveryAddress extends BaseUsersDeliveryAddress<UsersDeliveryAddress> {
	public static final UsersDeliveryAddress dao = new UsersDeliveryAddress();

	@Override
	public List<UsersDeliveryAddress> getAllData(UsersDeliveryAddress t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("select * from users_delivery_address uda where 1=1 ");
		ArrayList<Object> values = new ArrayList<>();
		if(t!=null&&!t.getAttrs().isEmpty()){
			if(t.getUserFrontId()!=null){
				sbSql.append(" and uda.user_front_id=?");
				values.add(t.getUserFrontId());
			}
		}
		return this.find(sbSql.toString(),values.toArray());
	}
}
