package com.mi2.model;

import com.base.model.BaseUsersFront;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersFront extends BaseUsersFront<UsersFront> {
	public static final UsersFront dao = new UsersFront();

	@Override
	public Page<UsersFront> getAllDataByPage(int pageNumber, int pageSize, UsersFront t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("from users_front uf where 1=1 ");
		ArrayList<Object> values = new ArrayList<>();
		if(t!=null&&!t.getAttrs().isEmpty()){
			String search_key = t.get("search_key");
			if(StrKit.notBlank(search_key)){
				sbSql.append(" and uf.login_name=? or uf.name like ? or uf.telephone=? or uf.email=?");
				values.add(search_key);
				values.add("%"+search_key+"%");
				values.add(search_key);
				values.add(search_key);
			}
			if(StrKit.notBlank(t.getUserStatus())){
				sbSql.append(" and uf.user_status=?");
				values.add(t.getUserStatus());
			}
		}
		return this.paginate(pageNumber,pageSize,"select * ",sbSql.toString(),values.toArray());
	}


	@Override
	public List<UsersFront> getAllData(UsersFront t) {
		StringBuilder sbSql = new StringBuilder();
		sbSql.append("select * from users_front uf where 1=1 ");
		ArrayList<Object> values = new ArrayList<>();
		if(null!=t&&!t.getAttrs().isEmpty()){
			if(StrKit.notBlank(t.getLoginName())){
				sbSql.append(" and uf.login_name=?");
				values.add(t.getLoginName());
			}
		}
		return this.find(sbSql.toString(),values.toArray());
	}
}
