package com.mi2.model;

import com.base.model.BaseUsersShoppingcar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersShoppingcar extends BaseUsersShoppingcar<UsersShoppingcar> {
	public static final UsersShoppingcar dao = new UsersShoppingcar();
}
