package com.mi2.model;

import com.base.model.BaseUsersSettleAcountsView;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersSettleAcountsView extends BaseUsersSettleAcountsView<UsersSettleAcountsView> {
	public static final UsersSettleAcountsView dao = new UsersSettleAcountsView();
}
