package com.mi2.model;

import com.base.model.BaseUsersOrdersDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersOrdersDetail extends BaseUsersOrdersDetail<UsersOrdersDetail> {
	public static final UsersOrdersDetail dao = new UsersOrdersDetail();
}
