package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOtherGoodsView<M extends BaseOtherGoodsView<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "OTHER_GOODS_VIEW";

	public final static String SQL = "SELECT * FROM OTHER_GOODS_VIEW WHERE 1=1 ";

	public void setGoodsBigTypeId(java.math.BigDecimal goodsBigTypeId) {
		set("GOODS_BIG_TYPE_ID", goodsBigTypeId);
	}

	public java.math.BigDecimal getGoodsBigTypeId() {
		return get("GOODS_BIG_TYPE_ID");
	}

	public void setGoodsBiglTypeName(java.lang.String goodsBiglTypeName) {
		set("GOODS_BIGL_TYPE_NAME", goodsBiglTypeName);
	}

	public java.lang.String getGoodsBiglTypeName() {
		return get("GOODS_BIGL_TYPE_NAME");
	}

	public void setGoodsSmallTypeName(java.lang.String goodsSmallTypeName) {
		set("GOODS_SMALL_TYPE_NAME", goodsSmallTypeName);
	}

	public java.lang.String getGoodsSmallTypeName() {
		return get("GOODS_SMALL_TYPE_NAME");
	}

	public void setGoodsSmallTypeRemark(java.lang.String goodsSmallTypeRemark) {
		set("GOODS_SMALL_TYPE_REMARK", goodsSmallTypeRemark);
	}

	public java.lang.String getGoodsSmallTypeRemark() {
		return get("GOODS_SMALL_TYPE_REMARK");
	}

	public void setGoodsSmallTypeImage(java.lang.String goodsSmallTypeImage) {
		set("GOODS_SMALL_TYPE_IMAGE", goodsSmallTypeImage);
	}

	public java.lang.String getGoodsSmallTypeImage() {
		return get("GOODS_SMALL_TYPE_IMAGE");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setGoodsSmallTypeId(java.math.BigDecimal goodsSmallTypeId) {
		set("GOODS_SMALL_TYPE_ID", goodsSmallTypeId);
	}

	public java.math.BigDecimal getGoodsSmallTypeId() {
		return get("GOODS_SMALL_TYPE_ID");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("GOODS_NAME", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("GOODS_NAME");
	}

	public void setGoodsFormerPrice(java.math.BigDecimal goodsFormerPrice) {
		set("GOODS_FORMER_PRICE", goodsFormerPrice);
	}

	public java.math.BigDecimal getGoodsFormerPrice() {
		return get("GOODS_FORMER_PRICE");
	}

	public void setGoodsNewPrice(java.math.BigDecimal goodsNewPrice) {
		set("GOODS_NEW_PRICE", goodsNewPrice);
	}

	public java.math.BigDecimal getGoodsNewPrice() {
		return get("GOODS_NEW_PRICE");
	}

	public void setGoodsStock(java.math.BigDecimal goodsStock) {
		set("GOODS_STOCK", goodsStock);
	}

	public java.math.BigDecimal getGoodsStock() {
		return get("GOODS_STOCK");
	}

	public void setGoodsSalesNum(java.math.BigDecimal goodsSalesNum) {
		set("GOODS_SALES_NUM", goodsSalesNum);
	}

	public java.math.BigDecimal getGoodsSalesNum() {
		return get("GOODS_SALES_NUM");
	}

	public void setGoodsPreviewImage(java.lang.String goodsPreviewImage) {
		set("GOODS_PREVIEW_IMAGE", goodsPreviewImage);
	}

	public java.lang.String getGoodsPreviewImage() {
		return get("GOODS_PREVIEW_IMAGE");
	}

	public void setAdapterAllPhone(java.lang.String adapterAllPhone) {
		set("ADAPTER_ALL_PHONE", adapterAllPhone);
	}

	public java.lang.String getAdapterAllPhone() {
		return get("ADAPTER_ALL_PHONE");
	}

	public void setAdaptPhoneTypeName(java.lang.String adaptPhoneTypeName) {
		set("ADAPT_PHONE_TYPE_NAME", adaptPhoneTypeName);
	}

	public java.lang.String getAdaptPhoneTypeName() {
		return get("ADAPT_PHONE_TYPE_NAME");
	}

	public void setAdaptPhoneTypeId(java.math.BigDecimal adaptPhoneTypeId) {
		set("ADAPT_PHONE_TYPE_ID", adaptPhoneTypeId);
	}

	public java.math.BigDecimal getAdaptPhoneTypeId() {
		return get("ADAPT_PHONE_TYPE_ID");
	}

}
