package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsImages<M extends BaseGoodsImages<M>> extends Model<M> implements IBean {

	public void setGoodsImagesId(java.math.BigDecimal goodsImagesId) {
		set("GOODS_IMAGES_ID", goodsImagesId);
	}

	public java.math.BigDecimal getGoodsImagesId() {
		return get("GOODS_IMAGES_ID");
	}

	public void setGoodsFatherImagesId(java.math.BigDecimal goodsFatherImagesId) {
		set("GOODS_FATHER_IMAGES_ID", goodsFatherImagesId);
	}

	public java.math.BigDecimal getGoodsFatherImagesId() {
		return get("GOODS_FATHER_IMAGES_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setGoodsImagesUri(java.lang.String goodsImagesUri) {
		set("GOODS_IMAGES_URI", goodsImagesUri);
	}

	public java.lang.String getGoodsImagesUri() {
		return get("GOODS_IMAGES_URI");
	}

}
