package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersOrdersDetail<M extends BaseUsersOrdersDetail<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "USERS_ORDERS_DETAIL";

	public final static String SQL = "SELECT * FROM USERS_ORDERS_DETAIL WHERE 1=1 ";

	public void setOrdersDetailsId(java.math.BigDecimal ordersDetailsId) {
		set("ORDERS_DETAILS_ID", ordersDetailsId);
	}

	public java.math.BigDecimal getOrdersDetailsId() {
		return get("ORDERS_DETAILS_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setOrdersId(java.math.BigDecimal ordersId) {
		set("ORDERS_ID", ordersId);
	}

	public java.math.BigDecimal getOrdersId() {
		return get("ORDERS_ID");
	}

	public void setCostNum(java.math.BigDecimal costNum) {
		set("COST_NUM", costNum);
	}

	public java.math.BigDecimal getCostNum() {
		return get("COST_NUM");
	}

	public void setCostPrice(java.math.BigDecimal costPrice) {
		set("COST_PRICE", costPrice);
	}

	public java.math.BigDecimal getCostPrice() {
		return get("COST_PRICE");
	}

	public void setPhoneVersionId(java.math.BigDecimal phoneVersionId) {
		set("PHONE_VERSION_ID", phoneVersionId);
	}

	public java.math.BigDecimal getPhoneVersionId() {
		return get("PHONE_VERSION_ID");
	}

}
