package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhoneSetmealDetail<M extends BasePhoneSetmealDetail<M>> extends Model<M> implements IBean {

	public void setPhoneSetmealDetailId(java.math.BigDecimal phoneSetmealDetailId) {
		set("PHONE_SETMEAL_DETAIL_ID", phoneSetmealDetailId);
	}

	public java.math.BigDecimal getPhoneSetmealDetailId() {
		return get("PHONE_SETMEAL_DETAIL_ID");
	}

	public void setPhoneSetmealId(java.math.BigDecimal phoneSetmealId) {
		set("PHONE_SETMEAL_ID", phoneSetmealId);
	}

	public java.math.BigDecimal getPhoneSetmealId() {
		return get("PHONE_SETMEAL_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setGoodsNum(java.math.BigDecimal goodsNum) {
		set("GOODS_NUM", goodsNum);
	}

	public java.math.BigDecimal getGoodsNum() {
		return get("GOODS_NUM");
	}

}
