package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersDeliveryAddress<M extends BaseUsersDeliveryAddress<M>> extends Model<M> implements IBean {

	public void setUsersDeliveryAddressId(java.math.BigDecimal usersDeliveryAddressId) {
		set("USERS_DELIVERY_ADDRESS_ID", usersDeliveryAddressId);
	}

	public java.math.BigDecimal getUsersDeliveryAddressId() {
		return get("USERS_DELIVERY_ADDRESS_ID");
	}

	public void setUserFrontId(java.math.BigDecimal userFrontId) {
		set("USER_FRONT_ID", userFrontId);
	}

	public java.math.BigDecimal getUserFrontId() {
		return get("USER_FRONT_ID");
	}

	public void setNAME(java.lang.String NAME) {
		set("NAME", NAME);
	}

	public java.lang.String getNAME() {
		return get("NAME");
	}

	public void setTELEPHONE(java.lang.String TELEPHONE) {
		set("TELEPHONE", TELEPHONE);
	}

	public java.lang.String getTELEPHONE() {
		return get("TELEPHONE");
	}

	public void setPOSTALCODE(java.lang.String POSTALCODE) {
		set("POSTALCODE", POSTALCODE);
	}

	public java.lang.String getPOSTALCODE() {
		return get("POSTALCODE");
	}

	public void setSTREET(java.lang.String STREET) {
		set("STREET", STREET);
	}

	public java.lang.String getSTREET() {
		return get("STREET");
	}

	public void setAddressLabel(java.lang.String addressLabel) {
		set("ADDRESS_LABEL", addressLabel);
	}

	public java.lang.String getAddressLabel() {
		return get("ADDRESS_LABEL");
	}

	public void setPROVINCE(java.lang.String PROVINCE) {
		set("PROVINCE", PROVINCE);
	}

	public java.lang.String getPROVINCE() {
		return get("PROVINCE");
	}

	public void setCITY(java.lang.String CITY) {
		set("CITY", CITY);
	}

	public java.lang.String getCITY() {
		return get("CITY");
	}

	public void setCOUNTY(java.lang.String COUNTY) {
		set("COUNTY", COUNTY);
	}

	public java.lang.String getCOUNTY() {
		return get("COUNTY");
	}

}
