package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersDeliveryAddress<M extends BaseUsersDeliveryAddress<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "USERS_DELIVERY_ADDRESS";

	public final static String SQL = "SELECT * FROM USERS_DELIVERY_ADDRESS WHERE 1=1 ";

	public void setUsersDeliveryAddressId(java.math.BigDecimal usersDeliveryAddressId) {
		set("USERS_DELIVERY_ADDRESS_ID", usersDeliveryAddressId);
	}

	public java.math.BigDecimal getUsersDeliveryAddressId() {
		return get("USERS_DELIVERY_ADDRESS_ID");
	}

	public void setUserFrontId(java.math.BigDecimal userFrontId) {
		set("USER_FRONT_ID", userFrontId);
	}

	public java.math.BigDecimal getUserFrontId() {
		return get("USER_FRONT_ID");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setTelephone(java.lang.String telephone) {
		set("TELEPHONE", telephone);
	}

	public java.lang.String getTelephone() {
		return get("TELEPHONE");
	}

	public void setPostalcode(java.lang.String postalcode) {
		set("POSTALCODE", postalcode);
	}

	public java.lang.String getPostalcode() {
		return get("POSTALCODE");
	}

	public void setStreet(java.lang.String street) {
		set("STREET", street);
	}

	public java.lang.String getStreet() {
		return get("STREET");
	}

	public void setAddressLabel(java.lang.String addressLabel) {
		set("ADDRESS_LABEL", addressLabel);
	}

	public java.lang.String getAddressLabel() {
		return get("ADDRESS_LABEL");
	}

	public void setProvince(java.lang.String province) {
		set("PROVINCE", province);
	}

	public java.lang.String getProvince() {
		return get("PROVINCE");
	}

	public void setCity(java.lang.String city) {
		set("CITY", city);
	}

	public java.lang.String getCity() {
		return get("CITY");
	}

	public void setCounty(java.lang.String county) {
		set("COUNTY", county);
	}

	public java.lang.String getCounty() {
		return get("COUNTY");
	}

}
