package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersFront<M extends BaseUsersFront<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "USERS_FRONT";

	public final static String SQL = "SELECT * FROM USERS_FRONT WHERE 1=1 ";

	public void setUserFrontId(java.math.BigDecimal userFrontId) {
		set("USER_FRONT_ID", userFrontId);
	}

	public java.math.BigDecimal getUserFrontId() {
		return get("USER_FRONT_ID");
	}

	public void setLoginName(java.lang.String loginName) {
		set("LOGIN_NAME", loginName);
	}

	public java.lang.String getLoginName() {
		return get("LOGIN_NAME");
	}

	public void setPassword(java.lang.String password) {
		set("PASSWORD", password);
	}

	public java.lang.String getPassword() {
		return get("PASSWORD");
	}

	public void setUserStatus(java.lang.String userStatus) {
		set("USER_STATUS", userStatus);
	}

	public java.lang.String getUserStatus() {
		return get("USER_STATUS");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setSex(java.lang.String sex) {
		set("SEX", sex);
	}

	public java.lang.String getSex() {
		return get("SEX");
	}

	public void setTelephone(java.lang.String telephone) {
		set("TELEPHONE", telephone);
	}

	public java.lang.String getTelephone() {
		return get("TELEPHONE");
	}

	public void setEmail(java.lang.String email) {
		set("EMAIL", email);
	}

	public java.lang.String getEmail() {
		return get("EMAIL");
	}

	public void setBirthday(java.util.Date birthday) {
		set("BIRTHDAY", birthday);
	}

	public java.util.Date getBirthday() {
		return get("BIRTHDAY");
	}

	public void setNickname(java.lang.String nickname) {
		set("NICKNAME", nickname);
	}

	public java.lang.String getNickname() {
		return get("NICKNAME");
	}

	public void setImg(java.lang.String img) {
		set("IMG", img);
	}

	public java.lang.String getImg() {
		return get("IMG");
	}

}
