package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhoneVersion<M extends BasePhoneVersion<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "PHONE_VERSION";

	public final static String SQL = "SELECT * FROM PHONE_VERSION WHERE 1=1 ";

	public void setPhoneGoodsId(java.math.BigDecimal phoneGoodsId) {
		set("PHONE_GOODS_ID", phoneGoodsId);
	}

	public java.math.BigDecimal getPhoneGoodsId() {
		return get("PHONE_GOODS_ID");
	}

	public void setGoodsAddributeValId(java.math.BigDecimal goodsAddributeValId) {
		set("GOODS_ADDRIBUTE_VAL_ID", goodsAddributeValId);
	}

	public java.math.BigDecimal getGoodsAddributeValId() {
		return get("GOODS_ADDRIBUTE_VAL_ID");
	}

	public void setModelId(java.math.BigDecimal modelId) {
		set("MODEL_ID", modelId);
	}

	public java.math.BigDecimal getModelId() {
		return get("MODEL_ID");
	}

	public void setPhoneFormerPrice(java.math.BigDecimal phoneFormerPrice) {
		set("PHONE_FORMER_PRICE", phoneFormerPrice);
	}

	public java.math.BigDecimal getPhoneFormerPrice() {
		return get("PHONE_FORMER_PRICE");
	}

	public void setPhoneNowPrice(java.math.BigDecimal phoneNowPrice) {
		set("PHONE_NOW_PRICE", phoneNowPrice);
	}

	public java.math.BigDecimal getPhoneNowPrice() {
		return get("PHONE_NOW_PRICE");
	}

	public void setPhoneStock(java.math.BigDecimal phoneStock) {
		set("PHONE_STOCK", phoneStock);
	}

	public java.math.BigDecimal getPhoneStock() {
		return get("PHONE_STOCK");
	}

	public void setPhoneSalesNum(java.math.BigDecimal phoneSalesNum) {
		set("PHONE_SALES_NUM", phoneSalesNum);
	}

	public java.math.BigDecimal getPhoneSalesNum() {
		return get("PHONE_SALES_NUM");
	}

	public void setPhonePreviewImage(java.lang.String phonePreviewImage) {
		set("PHONE_PREVIEW_IMAGE", phonePreviewImage);
	}

	public java.lang.String getPhonePreviewImage() {
		return get("PHONE_PREVIEW_IMAGE");
	}

}
