package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhoneGoodsView<M extends BasePhoneGoodsView<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "PHONE_GOODS_VIEW";

	public final static String SQL = "SELECT * FROM PHONE_GOODS_VIEW WHERE 1=1 ";

	public void setGoodsBiglTypeName(java.lang.String goodsBiglTypeName) {
		set("GOODS_BIGL_TYPE_NAME", goodsBiglTypeName);
	}

	public java.lang.String getGoodsBiglTypeName() {
		return get("GOODS_BIGL_TYPE_NAME");
	}

	public void setGoodsSmallTypeId(java.math.BigDecimal goodsSmallTypeId) {
		set("GOODS_SMALL_TYPE_ID", goodsSmallTypeId);
	}

	public java.math.BigDecimal getGoodsSmallTypeId() {
		return get("GOODS_SMALL_TYPE_ID");
	}

	public void setGoodsBigTypeId(java.math.BigDecimal goodsBigTypeId) {
		set("GOODS_BIG_TYPE_ID", goodsBigTypeId);
	}

	public java.math.BigDecimal getGoodsBigTypeId() {
		return get("GOODS_BIG_TYPE_ID");
	}

	public void setGoodsSmallTypeName(java.lang.String goodsSmallTypeName) {
		set("GOODS_SMALL_TYPE_NAME", goodsSmallTypeName);
	}

	public java.lang.String getGoodsSmallTypeName() {
		return get("GOODS_SMALL_TYPE_NAME");
	}

	public void setGoodsSmallTypeRemark(java.lang.String goodsSmallTypeRemark) {
		set("GOODS_SMALL_TYPE_REMARK", goodsSmallTypeRemark);
	}

	public java.lang.String getGoodsSmallTypeRemark() {
		return get("GOODS_SMALL_TYPE_REMARK");
	}

	public void setGoodsSmallTypeImage(java.lang.String goodsSmallTypeImage) {
		set("GOODS_SMALL_TYPE_IMAGE", goodsSmallTypeImage);
	}

	public java.lang.String getGoodsSmallTypeImage() {
		return get("GOODS_SMALL_TYPE_IMAGE");
	}

	public void setModelId(java.math.BigDecimal modelId) {
		set("MODEL_ID", modelId);
	}

	public java.math.BigDecimal getModelId() {
		return get("MODEL_ID");
	}

	public void setPhoneModelId(java.math.BigDecimal phoneModelId) {
		set("PHONE_MODEL_ID", phoneModelId);
	}

	public java.math.BigDecimal getPhoneModelId() {
		return get("PHONE_MODEL_ID");
	}

	public void setPhoneModelName(java.lang.String phoneModelName) {
		set("PHONE_MODEL_NAME", phoneModelName);
	}

	public java.lang.String getPhoneModelName() {
		return get("PHONE_MODEL_NAME");
	}

	public void setPhoneVersionId(java.math.BigDecimal phoneVersionId) {
		set("PHONE_VERSION_ID", phoneVersionId);
	}

	public java.math.BigDecimal getPhoneVersionId() {
		return get("PHONE_VERSION_ID");
	}

	public void setPhoneVersionName(java.lang.String phoneVersionName) {
		set("PHONE_VERSION_NAME", phoneVersionName);
	}

	public java.lang.String getPhoneVersionName() {
		return get("PHONE_VERSION_NAME");
	}

	public void setPhoneFormerPrice(java.math.BigDecimal phoneFormerPrice) {
		set("PHONE_FORMER_PRICE", phoneFormerPrice);
	}

	public java.math.BigDecimal getPhoneFormerPrice() {
		return get("PHONE_FORMER_PRICE");
	}

	public void setPhoneNowPrice(java.math.BigDecimal phoneNowPrice) {
		set("PHONE_NOW_PRICE", phoneNowPrice);
	}

	public java.math.BigDecimal getPhoneNowPrice() {
		return get("PHONE_NOW_PRICE");
	}

	public void setPhoneStock(java.math.BigDecimal phoneStock) {
		set("PHONE_STOCK", phoneStock);
	}

	public java.math.BigDecimal getPhoneStock() {
		return get("PHONE_STOCK");
	}

	public void setPhoneSalesNum(java.math.BigDecimal phoneSalesNum) {
		set("PHONE_SALES_NUM", phoneSalesNum);
	}

	public java.math.BigDecimal getPhoneSalesNum() {
		return get("PHONE_SALES_NUM");
	}

	public void setPhonePreviewImage(java.lang.String phonePreviewImage) {
		set("PHONE_PREVIEW_IMAGE", phonePreviewImage);
	}

	public java.lang.String getPhonePreviewImage() {
		return get("PHONE_PREVIEW_IMAGE");
	}

	public void setPhoneGoodsId(java.math.BigDecimal phoneGoodsId) {
		set("PHONE_GOODS_ID", phoneGoodsId);
	}

	public java.math.BigDecimal getPhoneGoodsId() {
		return get("PHONE_GOODS_ID");
	}

}
