package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhoneSetmeal<M extends BasePhoneSetmeal<M>> extends Model<M> implements IBean {

	public void setPhoneSetmealId(java.math.BigDecimal phoneSetmealId) {
		set("PHONE_SETMEAL_ID", phoneSetmealId);
	}

	public java.math.BigDecimal getPhoneSetmealId() {
		return get("PHONE_SETMEAL_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setPhoneSetmealName(java.lang.String phoneSetmealName) {
		set("PHONE_SETMEAL_NAME", phoneSetmealName);
	}

	public java.lang.String getPhoneSetmealName() {
		return get("PHONE_SETMEAL_NAME");
	}

	public void setSetmealGoodsNum(java.math.BigDecimal setmealGoodsNum) {
		set("SETMEAL_GOODS_NUM", setmealGoodsNum);
	}

	public java.math.BigDecimal getSetmealGoodsNum() {
		return get("SETMEAL_GOODS_NUM");
	}

	public void setSetmealPrice(java.math.BigDecimal setmealPrice) {
		set("SETMEAL_PRICE", setmealPrice);
	}

	public java.math.BigDecimal getSetmealPrice() {
		return get("SETMEAL_PRICE");
	}

}
