package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhoneModel<M extends BasePhoneModel<M>> extends Model<M> implements IBean {

	public void setPhoneModelId(java.math.BigDecimal phoneModelId) {
		set("PHONE_MODEL_ID", phoneModelId);
	}

	public java.math.BigDecimal getPhoneModelId() {
		return get("PHONE_MODEL_ID");
	}

	public void setGoodsAddributeValId(java.math.BigDecimal goodsAddributeValId) {
		set("GOODS_ADDRIBUTE_VAL_ID", goodsAddributeValId);
	}

	public java.math.BigDecimal getGoodsAddributeValId() {
		return get("GOODS_ADDRIBUTE_VAL_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

}
