package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsAdapterPhone<M extends BaseGoodsAdapterPhone<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "GOODS_ADAPTER_PHONE";

	public final static String SQL = "SELECT * FROM GOODS_ADAPTER_PHONE WHERE 1=1 ";

	public void setGoodsSmallTypeId(java.math.BigDecimal goodsSmallTypeId) {
		set("GOODS_SMALL_TYPE_ID", goodsSmallTypeId);
	}

	public java.math.BigDecimal getGoodsSmallTypeId() {
		return get("GOODS_SMALL_TYPE_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

}
