package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "GOODS";

	public final static String SQL = "SELECT * FROM GOODS WHERE 1=1 ";

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setGoodsSmallTypeId(java.math.BigDecimal goodsSmallTypeId) {
		set("GOODS_SMALL_TYPE_ID", goodsSmallTypeId);
	}

	public java.math.BigDecimal getGoodsSmallTypeId() {
		return get("GOODS_SMALL_TYPE_ID");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("GOODS_NAME", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("GOODS_NAME");
	}

	public void setGoodsFormerPrice(java.math.BigDecimal goodsFormerPrice) {
		set("GOODS_FORMER_PRICE", goodsFormerPrice);
	}

	public java.math.BigDecimal getGoodsFormerPrice() {
		return get("GOODS_FORMER_PRICE");
	}

	public void setGoodsNewPrice(java.math.BigDecimal goodsNewPrice) {
		set("GOODS_NEW_PRICE", goodsNewPrice);
	}

	public java.math.BigDecimal getGoodsNewPrice() {
		return get("GOODS_NEW_PRICE");
	}

	public void setGoodsStock(java.math.BigDecimal goodsStock) {
		set("GOODS_STOCK", goodsStock);
	}

	public java.math.BigDecimal getGoodsStock() {
		return get("GOODS_STOCK");
	}

	public void setGoodsSalesNum(java.math.BigDecimal goodsSalesNum) {
		set("GOODS_SALES_NUM", goodsSalesNum);
	}

	public java.math.BigDecimal getGoodsSalesNum() {
		return get("GOODS_SALES_NUM");
	}

	public void setGoodsPreviewImage(java.lang.String goodsPreviewImage) {
		set("GOODS_PREVIEW_IMAGE", goodsPreviewImage);
	}

	public java.lang.String getGoodsPreviewImage() {
		return get("GOODS_PREVIEW_IMAGE");
	}

	public void setAdapterAllPhone(java.lang.String adapterAllPhone) {
		set("ADAPTER_ALL_PHONE", adapterAllPhone);
	}

	public java.lang.String getAdapterAllPhone() {
		return get("ADAPTER_ALL_PHONE");
	}

}
