package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersShoppingcar<M extends BaseUsersShoppingcar<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "USERS_SHOPPINGCAR";

	public final static String SQL = "SELECT * FROM USERS_SHOPPINGCAR WHERE 1=1 ";

	public void setUsersShoppingId(java.math.BigDecimal usersShoppingId) {
		set("USERS_SHOPPING_ID", usersShoppingId);
	}

	public java.math.BigDecimal getUsersShoppingId() {
		return get("USERS_SHOPPING_ID");
	}

	public void setUserFrontId(java.math.BigDecimal userFrontId) {
		set("USER_FRONT_ID", userFrontId);
	}

	public java.math.BigDecimal getUserFrontId() {
		return get("USER_FRONT_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setShoppingNum(java.math.BigDecimal shoppingNum) {
		set("SHOPPING_NUM", shoppingNum);
	}

	public java.math.BigDecimal getShoppingNum() {
		return get("SHOPPING_NUM");
	}

	public void setShoppingTime(java.util.Date shoppingTime) {
		set("SHOPPING_TIME", shoppingTime);
	}

	public java.util.Date getShoppingTime() {
		return get("SHOPPING_TIME");
	}

	public void setPhoneGoodsId(java.math.BigDecimal phoneGoodsId) {
		set("PHONE_GOODS_ID", phoneGoodsId);
	}

	public java.math.BigDecimal getPhoneGoodsId() {
		return get("PHONE_GOODS_ID");
	}

}
