package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersBackstage<M extends BaseUsersBackstage<M>> extends Model<M> implements IBean {

	public void setUsersBackstageId(java.math.BigDecimal usersBackstageId) {
		set("USERS_BACKSTAGE_ID", usersBackstageId);
	}

	public java.math.BigDecimal getUsersBackstageId() {
		return get("USERS_BACKSTAGE_ID");
	}

	public void setRoleGroupId(java.math.BigDecimal roleGroupId) {
		set("ROLE_GROUP_ID", roleGroupId);
	}

	public java.math.BigDecimal getRoleGroupId() {
		return get("ROLE_GROUP_ID");
	}

	public void setSysUserName(java.lang.String sysUserName) {
		set("SYS_USER_NAME", sysUserName);
	}

	public java.lang.String getSysUserName() {
		return get("SYS_USER_NAME");
	}

	public void setSysUserPassword(java.lang.String sysUserPassword) {
		set("SYS_USER_PASSWORD", sysUserPassword);
	}

	public java.lang.String getSysUserPassword() {
		return get("SYS_USER_PASSWORD");
	}

	public void setNAME(java.lang.String NAME) {
		set("NAME", NAME);
	}

	public java.lang.String getNAME() {
		return get("NAME");
	}

	public void setSEX(java.lang.String SEX) {
		set("SEX", SEX);
	}

	public java.lang.String getSEX() {
		return get("SEX");
	}

	public void setTELEPHONE(java.lang.String TELEPHONE) {
		set("TELEPHONE", TELEPHONE);
	}

	public java.lang.String getTELEPHONE() {
		return get("TELEPHONE");
	}

	public void setEMAIL(java.lang.String EMAIL) {
		set("EMAIL", EMAIL);
	}

	public java.lang.String getEMAIL() {
		return get("EMAIL");
	}

	public void setBIRTHDAY(java.util.Date BIRTHDAY) {
		set("BIRTHDAY", BIRTHDAY);
	}

	public java.util.Date getBIRTHDAY() {
		return get("BIRTHDAY");
	}

	public void setNICKNAME(java.lang.String NICKNAME) {
		set("NICKNAME", NICKNAME);
	}

	public java.lang.String getNICKNAME() {
		return get("NICKNAME");
	}

	public void setSTATUS(java.lang.String STATUS) {
		set("STATUS", STATUS);
	}

	public java.lang.String getSTATUS() {
		return get("STATUS");
	}

	public void setIMG(java.lang.String IMG) {
		set("IMG", IMG);
	}

	public java.lang.String getIMG() {
		return get("IMG");
	}

}
