package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersShopcarSetmealGoods<M extends BaseUsersShopcarSetmealGoods<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "USERS_SHOPCAR_SETMEAL_GOODS";

	public final static String SQL = "SELECT * FROM USERS_SHOPCAR_SETMEAL_GOODS WHERE 1=1 ";

	public void setUsersShopcarSetmealGoodsId(java.math.BigDecimal usersShopcarSetmealGoodsId) {
		set("USERS_SHOPCAR_SETMEAL_GOODS_ID", usersShopcarSetmealGoodsId);
	}

	public java.math.BigDecimal getUsersShopcarSetmealGoodsId() {
		return get("USERS_SHOPCAR_SETMEAL_GOODS_ID");
	}

	public void setUsersShoppingId(java.math.BigDecimal usersShoppingId) {
		set("USERS_SHOPPING_ID", usersShoppingId);
	}

	public java.math.BigDecimal getUsersShoppingId() {
		return get("USERS_SHOPPING_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setGoodsColorId(java.math.BigDecimal goodsColorId) {
		set("GOODS_COLOR_ID", goodsColorId);
	}

	public java.math.BigDecimal getGoodsColorId() {
		return get("GOODS_COLOR_ID");
	}

	public void setGoodsNum(java.math.BigDecimal goodsNum) {
		set("GOODS_NUM", goodsNum);
	}

	public java.math.BigDecimal getGoodsNum() {
		return get("GOODS_NUM");
	}

	public void setStatus(java.lang.String status) {
		set("STATUS", status);
	}

	public java.lang.String getStatus() {
		return get("STATUS");
	}

	public void setAdaptPhoneTypeId(java.math.BigDecimal adaptPhoneTypeId) {
		set("ADAPT_PHONE_TYPE_ID", adaptPhoneTypeId);
	}

	public java.math.BigDecimal getAdaptPhoneTypeId() {
		return get("ADAPT_PHONE_TYPE_ID");
	}

}
