package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersOrdersDetail<M extends BaseUsersOrdersDetail<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "USERS_ORDERS_DETAIL";

	public final static String SQL = "SELECT * FROM USERS_ORDERS_DETAIL WHERE 1=1 ";

	public void setOrdersDetailsId(java.math.BigDecimal ordersDetailsId) {
		set("ORDERS_DETAILS_ID", ordersDetailsId);
	}

	public java.math.BigDecimal getOrdersDetailsId() {
		return get("ORDERS_DETAILS_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setOrdersId(java.math.BigDecimal ordersId) {
		set("ORDERS_ID", ordersId);
	}

	public java.math.BigDecimal getOrdersId() {
		return get("ORDERS_ID");
	}

	public void setCostNum(java.math.BigDecimal costNum) {
		set("COST_NUM", costNum);
	}

	public java.math.BigDecimal getCostNum() {
		return get("COST_NUM");
	}

	public void setCostPrice(java.math.BigDecimal costPrice) {
		set("COST_PRICE", costPrice);
	}

	public java.math.BigDecimal getCostPrice() {
		return get("COST_PRICE");
	}

	public void setPhoneGoodsId(java.math.BigDecimal phoneGoodsId) {
		set("PHONE_GOODS_ID", phoneGoodsId);
	}

	public java.math.BigDecimal getPhoneGoodsId() {
		return get("PHONE_GOODS_ID");
	}

	public void setGoodsColorId(java.math.BigDecimal goodsColorId) {
		set("GOODS_COLOR_ID", goodsColorId);
	}

	public java.math.BigDecimal getGoodsColorId() {
		return get("GOODS_COLOR_ID");
	}

	public void setAdaptPhoneTypeId(java.math.BigDecimal adaptPhoneTypeId) {
		set("ADAPT_PHONE_TYPE_ID", adaptPhoneTypeId);
	}

	public java.math.BigDecimal getAdaptPhoneTypeId() {
		return get("ADAPT_PHONE_TYPE_ID");
	}

	public void setPhoneSetmealId(java.math.BigDecimal phoneSetmealId) {
		set("PHONE_SETMEAL_ID", phoneSetmealId);
	}

	public java.math.BigDecimal getPhoneSetmealId() {
		return get("PHONE_SETMEAL_ID");
	}

}
