package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsColor<M extends BaseGoodsColor<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "GOODS_COLOR";

	public final static String SQL = "SELECT * FROM GOODS_COLOR WHERE 1=1 ";

	public void setGoodsColorId(java.math.BigDecimal goodsColorId) {
		set("GOODS_COLOR_ID", goodsColorId);
	}

	public java.math.BigDecimal getGoodsColorId() {
		return get("GOODS_COLOR_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setGoodsAddributeValId(java.math.BigDecimal goodsAddributeValId) {
		set("GOODS_ADDRIBUTE_VAL_ID", goodsAddributeValId);
	}

	public java.math.BigDecimal getGoodsAddributeValId() {
		return get("GOODS_ADDRIBUTE_VAL_ID");
	}

	public void setGoodsColorImgUrl(java.lang.String goodsColorImgUrl) {
		set("GOODS_COLOR_IMG_URL", goodsColorImgUrl);
	}

	public java.lang.String getGoodsColorImgUrl() {
		return get("GOODS_COLOR_IMG_URL");
	}

}
