package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsAddributeVal<M extends BaseGoodsAddributeVal<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "GOODS_ADDRIBUTE_VAL";

	public final static String SQL = "SELECT * FROM GOODS_ADDRIBUTE_VAL WHERE 1=1 ";

	public void setGoodsAddributeValId(java.math.BigDecimal goodsAddributeValId) {
		set("GOODS_ADDRIBUTE_VAL_ID", goodsAddributeValId);
	}

	public java.math.BigDecimal getGoodsAddributeValId() {
		return get("GOODS_ADDRIBUTE_VAL_ID");
	}

	public void setGoodsAddributeId(java.math.BigDecimal goodsAddributeId) {
		set("GOODS_ADDRIBUTE_ID", goodsAddributeId);
	}

	public java.math.BigDecimal getGoodsAddributeId() {
		return get("GOODS_ADDRIBUTE_ID");
	}

	public void setGoodsAddributeValName(java.lang.String goodsAddributeValName) {
		set("GOODS_ADDRIBUTE_VAL_NAME", goodsAddributeValName);
	}

	public java.lang.String getGoodsAddributeValName() {
		return get("GOODS_ADDRIBUTE_VAL_NAME");
	}

	public void setGoodsColorCode(java.lang.String goodsColorCode) {
		set("GOODS_COLOR_CODE", goodsColorCode);
	}

	public java.lang.String getGoodsColorCode() {
		return get("GOODS_COLOR_CODE");
	}

}
