package com.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.Page;

import java.lang.reflect.Field;
import java.util.List;

/**
 * 该类中定义Service层调用dao层的通用方法的扩展
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModel<M extends BaseModel<M>> extends Model<M> {

    public List<M> getAllData(M t){
        if(null==t)return null;
        try {
            Field field = t.getClass().getField("SQL");
            if(null==field)return null;
            String sql = field.get(t).toString();
            return this.find(sql);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public Page<M> getAllDataByPage(int pageNumber, int pageSize, M t){
        if(null==t)return null;
        try {
            Field field = t.getClass().getField("TABLE_NAME");
            if(null==field)return null;
            String tableName = field.get(t).toString();
            return this.paginate(pageNumber,pageSize,"SELECT * ","FROM "+tableName+" WHERE 1=1 ");
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}
