package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhoneVersion<M extends BasePhoneVersion<M>> extends Model<M> implements IBean {

	public void setPhoneVersionId(java.math.BigDecimal phoneVersionId) {
		set("PHONE_VERSION_ID", phoneVersionId);
	}

	public java.math.BigDecimal getPhoneVersionId() {
		return get("PHONE_VERSION_ID");
	}

	public void setGoodsAddributeValId(java.math.BigDecimal goodsAddributeValId) {
		set("GOODS_ADDRIBUTE_VAL_ID", goodsAddributeValId);
	}

	public java.math.BigDecimal getGoodsAddributeValId() {
		return get("GOODS_ADDRIBUTE_VAL_ID");
	}

	public void setPhoneModelId(java.math.BigDecimal phoneModelId) {
		set("PHONE_MODEL_ID", phoneModelId);
	}

	public java.math.BigDecimal getPhoneModelId() {
		return get("PHONE_MODEL_ID");
	}

	public void setPhoneFormerPrice(java.math.BigDecimal phoneFormerPrice) {
		set("PHONE_FORMER_PRICE", phoneFormerPrice);
	}

	public java.math.BigDecimal getPhoneFormerPrice() {
		return get("PHONE_FORMER_PRICE");
	}

	public void setPhoneNowPrice(java.math.BigDecimal phoneNowPrice) {
		set("PHONE_NOW_PRICE", phoneNowPrice);
	}

	public java.math.BigDecimal getPhoneNowPrice() {
		return get("PHONE_NOW_PRICE");
	}

}
