package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsImages<M extends BaseGoodsImages<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "GOODS_IMAGES";

	public final static String SQL = "SELECT * FROM GOODS_IMAGES WHERE 1=1 ";

	public void setGoodsImagesId(java.math.BigDecimal goodsImagesId) {
		set("GOODS_IMAGES_ID", goodsImagesId);
	}

	public java.math.BigDecimal getGoodsImagesId() {
		return get("GOODS_IMAGES_ID");
	}

	public void setGoodsFatherImagesId(java.math.BigDecimal goodsFatherImagesId) {
		set("GOODS_FATHER_IMAGES_ID", goodsFatherImagesId);
	}

	public java.math.BigDecimal getGoodsFatherImagesId() {
		return get("GOODS_FATHER_IMAGES_ID");
	}

	public void setGoodsColorId(java.math.BigDecimal goodsColorId) {
		set("GOODS_COLOR_ID", goodsColorId);
	}

	public java.math.BigDecimal getGoodsColorId() {
		return get("GOODS_COLOR_ID");
	}

	public void setGoodsImagesUri(java.lang.String goodsImagesUri) {
		set("GOODS_IMAGES_URI", goodsImagesUri);
	}

	public java.lang.String getGoodsImagesUri() {
		return get("GOODS_IMAGES_URI");
	}

}
