package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersShoppingcar<M extends BaseUsersShoppingcar<M>> extends Model<M> implements IBean {

	public void setUsersShoppingId(java.math.BigDecimal usersShoppingId) {
		set("USERS_SHOPPING_ID", usersShoppingId);
	}

	public java.math.BigDecimal getUsersShoppingId() {
		return get("USERS_SHOPPING_ID");
	}

	public void setUserFrontId(java.math.BigDecimal userFrontId) {
		set("USER_FRONT_ID", userFrontId);
	}

	public java.math.BigDecimal getUserFrontId() {
		return get("USER_FRONT_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setShoppingNum(java.math.BigDecimal shoppingNum) {
		set("SHOPPING_NUM", shoppingNum);
	}

	public java.math.BigDecimal getShoppingNum() {
		return get("SHOPPING_NUM");
	}

	public void setShoppingTime(java.util.Date shoppingTime) {
		set("SHOPPING_TIME", shoppingTime);
	}

	public java.util.Date getShoppingTime() {
		return get("SHOPPING_TIME");
	}

	public void setPhoneVersionId(java.math.BigDecimal phoneVersionId) {
		set("PHONE_VERSION_ID", phoneVersionId);
	}

	public java.math.BigDecimal getPhoneVersionId() {
		return get("PHONE_VERSION_ID");
	}

}
