package com.base.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public void setMenuId(java.math.BigDecimal menuId) {
		set("MENU_ID", menuId);
	}

	public java.math.BigDecimal getMenuId() {
		return get("MENU_ID");
	}

	public void setMenuParentId(java.math.BigDecimal menuParentId) {
		set("MENU_PARENT_ID", menuParentId);
	}

	public java.math.BigDecimal getMenuParentId() {
		return get("MENU_PARENT_ID");
	}

	public void setMenuName(java.lang.String menuName) {
		set("MENU_NAME", menuName);
	}

	public java.lang.String getMenuName() {
		return get("MENU_NAME");
	}

	public void setMenuSortIndex(java.math.BigDecimal menuSortIndex) {
		set("MENU_SORT_INDEX", menuSortIndex);
	}

	public java.math.BigDecimal getMenuSortIndex() {
		return get("MENU_SORT_INDEX");
	}

	public void setMenuHint(java.lang.String menuHint) {
		set("MENU_HINT", menuHint);
	}

	public java.lang.String getMenuHint() {
		return get("MENU_HINT");
	}

	public void setMenuVisible(java.lang.String menuVisible) {
		set("MENU_VISIBLE", menuVisible);
	}

	public java.lang.String getMenuVisible() {
		return get("MENU_VISIBLE");
	}

	public void setMenuIcon(java.lang.String menuIcon) {
		set("MENU_ICON", menuIcon);
	}

	public java.lang.String getMenuIcon() {
		return get("MENU_ICON");
	}

	public void setMenuUrl(java.lang.String menuUrl) {
		set("MENU_URL", menuUrl);
	}

	public java.lang.String getMenuUrl() {
		return get("MENU_URL");
	}

}
