package com.base.model;

import com.jfinal.plugin.activerecord.IBean;

/**
 * MyGenerated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersSettleAcountsView<M extends BaseUsersSettleAcountsView<M>> extends BaseModel<M> implements IBean {

	public final static String TABLE_NAME = "USERS_SETTLE_ACOUNTS_VIEW";

	public final static String SQL = "SELECT * FROM USERS_SETTLE_ACOUNTS_VIEW WHERE 1=1 ";

	public void setUserFrontId(java.math.BigDecimal userFrontId) {
		set("USER_FRONT_ID", userFrontId);
	}

	public java.math.BigDecimal getUserFrontId() {
		return get("USER_FRONT_ID");
	}

	public void setGoodsId(java.math.BigDecimal goodsId) {
		set("GOODS_ID", goodsId);
	}

	public java.math.BigDecimal getGoodsId() {
		return get("GOODS_ID");
	}

	public void setCostNum(java.math.BigDecimal costNum) {
		set("COST_NUM", costNum);
	}

	public java.math.BigDecimal getCostNum() {
		return get("COST_NUM");
	}

	public void setCostPrice(java.math.BigDecimal costPrice) {
		set("COST_PRICE", costPrice);
	}

	public java.math.BigDecimal getCostPrice() {
		return get("COST_PRICE");
	}

	public void setPhoneGoodsId(java.math.BigDecimal phoneGoodsId) {
		set("PHONE_GOODS_ID", phoneGoodsId);
	}

	public java.math.BigDecimal getPhoneGoodsId() {
		return get("PHONE_GOODS_ID");
	}

	public void setGoodsColorId(java.math.BigDecimal goodsColorId) {
		set("GOODS_COLOR_ID", goodsColorId);
	}

	public java.math.BigDecimal getGoodsColorId() {
		return get("GOODS_COLOR_ID");
	}

	public void setAdaptPhoneTypeId(java.math.BigDecimal adaptPhoneTypeId) {
		set("ADAPT_PHONE_TYPE_ID", adaptPhoneTypeId);
	}

	public java.math.BigDecimal getAdaptPhoneTypeId() {
		return get("ADAPT_PHONE_TYPE_ID");
	}

}
